In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
placer = pd.read_csv('//content/drive/MyDrive/AI Hackathon/placer/placer.csv')

In [ ]:
validation = pd.read_csv('/content/drive/MyDrive/AI Hackathon/validation_set.txt', sep=';', header = None)
validation.columns = ['time','energy','nitrogen_Nm3h']

In [ ]:
placer['ENDTIME'] = pd.to_datetime(placer['ENDTIME'],utc=True)

In [ ]:
task_full_blanks = pd.read_csv('/content/drive/MyDrive/AI Hackathon/task_full_blanks.txt', sep=';', header = None)
task_full_blanks.columns = ['time','energy','nitrogen_Nm3h']

In [ ]:
placer = placer[260224:327769]
del placer['Unnamed: 0']

In [ ]:
placer.reset_index(inplace=True, drop=True)
placer.index = placer.index
print(placer.head())

              PCBID           RECIPENAME  SIDE            STARTTIME  \
0  9781121080058881  1032367-03_NXT3_TL4   0.0  2022-10-11 19:52:44   
1  9781121080058877  1032367-03_NXT3_TL4   0.0  2022-10-11 19:52:32   
2  9781121080058880  1032367-03_NXT3_TL4   0.0  2022-10-11 19:52:57   
3  9781121080058879  1032367-03_NXT3_TL4   0.0  2022-10-11 19:52:57   
4  9781121080058878  1032367-03_NXT3_TL4   0.0  2022-10-11 19:53:04   

                    ENDTIME  MODULENO  NUMCOMP  NUMBLOCKS  NUMERRORS  
0 2022-10-11 19:53:09+00:00       6.0     40.0        1.0        0.0  
1 2022-10-11 19:53:10+00:00       1.0    165.0        1.0        1.0  
2 2022-10-11 19:53:28+00:00       5.0     40.0        1.0        0.0  
3 2022-10-11 19:53:31+00:00       4.0     75.0        1.0        0.0  
4 2022-10-11 19:53:35+00:00       3.0    135.0        1.0        0.0  


In [ ]:
validation = validation[0:16514]
validation.head()

time      energy  nitrogen_Nm3h
0  2022-10-11 19:50:30+00:00   9019.3995      19.440000
1  2022-10-11 19:50:45+00:00   6296.4840      19.428333
2  2022-10-11 19:51:00+00:00  15479.6640      19.585000
3  2022-10-11 19:51:15+00:00  11585.6500      20.127692
4  2022-10-11 19:51:30+00:00   6701.3010      19.685000

In [ ]:
validation['time'] = pd.to_datetime(validation['time'],utc=True)

In [ ]:
placer["F_Data"]=None
for i in range(0,1000):
  for j in range(1,5000):
    if(placer.iloc[i]["ENDTIME"] < validation.iloc[j]["time"] and placer.iloc[i]["ENDTIME"] > validation.iloc[j-1]["time"]):
      placer.at[i, 'F_data'] = j
      break

In [ ]:
placer[0:1000]

PCBID           RECIPENAME  SIDE            STARTTIME  \
0    9781121080058881  1032367-03_NXT3_TL4   0.0  2022-10-11 19:52:44   
1    9781121080058877  1032367-03_NXT3_TL4   0.0  2022-10-11 19:52:32   
2    9781121080058880  1032367-03_NXT3_TL4   0.0  2022-10-11 19:52:57   
3    9781121080058879  1032367-03_NXT3_TL4   0.0  2022-10-11 19:52:57   
4    9781121080058878  1032367-03_NXT3_TL4   0.0  2022-10-11 19:53:04   
..                ...                  ...   ...                  ...   
995  9779274060008763  9054480-05_NXT3_TL4   0.0  2022-10-11 21:22:10   
996  9779274060008653  9054480-05_NXT3_TL4   0.0  2022-10-11 21:22:06   
997  9779274060008761  9054480-05_NXT3_TL4   0.0  2022-10-11 21:22:10   
998  9779274060008759  9054480-05_NXT3_TL4   0.0  2022-10-11 21:22:10   
999  9779274060008757  9054480-05_NXT3_TL4   0.0  2022-10-11 21:22:09   

                      ENDTIME  MODULENO  NUMCOMP  NUMBLOCKS  NUMERRORS F_Data  \
0   2022-10-11 19:53:09+00:00       6.0     40.0        1.0        0.0   None   
1   2022-10-11 19:53:10+00:00       1.0    165.0        1.0        1.0   None   
2   2022-10-11 19:53:28+00:00       5.0     40.0        1.0        0.0   None   
3   2022-10-11 19:53:31+00:00       4.0     75.0        1.0        0.0   None   
4   2022-10-11 19:53:35+00:00       3.0    135.0        1.0        0.0   None   
..                        ...       ...      ...        ...        ...    ...   
995 2022-10-11 21:22:15+00:00       3.0     16.0        2.0        0.0   None   
996 2022-10-11 21:22:17+00:00       8.0     10.0        2.0        0.0   None   
997 2022-10-11 21:22:19+00:00       4.0     18.0        2.0        0.0   None   
998 2022-10-11 21:22:20+00:00       5.0     22.0        2.0        0.0   None   
999 2022-10-11 21:22:21+00:00       6.0     28.0        2.0        0.0   None   

     F_data  
0      11.0  
1      11.0  
2      12.0  
3      13.0  
4      13.0  
..      ...  
995    23.0  
996    23.0  
997    23.0  
998    23.0  
999    23.0  

[1000 rows x 11 columns]

In [ ]:
import matplotlib.pyplot as plt
import pandas as pd
from keras import models, layers

In [ ]:
x = np.array(placer[['MODULENO','NUMCOMP','NUMBLOCKS','NUMERRORS']])

In [ ]:
y = []

In [ ]:
for i in range(0,1000):
  for j in range(11,23):
    print(placer.iloc[i]["F_data"])
    if(placer.iloc[i]["F_data"]==j):
      y.append(validation.iloc[i][['energy','nitrogen_Nm3h']])

Streaming output truncated to the last 5000 lines.
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0
23.0

In [ ]:
y = np.array(y)

In [ ]:
y

array([[9019.3995, 19.44],
       [6296.484, 19.42833333333333],
       [15479.664, 19.585],
       [11585.65, 20.12769230769231],
       [6701.301, 19.685],
       [9088.583, 20.792857142857144],
       [16038.693, 21.81384615384616],
       [9077.342, 21.08857142857143],
       [7049.1325, 21.680000000000003],
       [11508.634, 22.2175],
       [8086.886, 21.78230769230769],
       [10072.1025, 21.92],
       [9001.401, 21.68],
       [5611.166, 20.29769230769231],
       [1887.989, 21.038571428571423],
       [17724.4535, 21.135714285714283],
       [4454.538, 21.14833333333333],
       [10278.756, 19.86642857142857],
       [9071.1825, 19.14555555555556],
       [1884.401, 19.121111111111112],
       [4634.284, 18.50076923076924],
       [5824.576499999999, 17.95111111111111],
       [1846.849, 11.412000000000004],
       [151.40249999999995, 0.165],
       [149.6085, 0.6525],
       [148.4725, 0.2],
       [149.37, 0.2477777777777777],
       [151.7615, 0.2681818181818181],
     

In [ ]:
y = np.flip(y)
y

array([[9019.3995, 19.44],
       [6296.484, 19.42833333333333],
       [15479.664, 19.585],
       [11585.65, 20.12769230769231],
       [6701.301, 19.685],
       [9088.583, 20.792857142857144],
       [16038.693, 21.81384615384616],
       [9077.342, 21.08857142857143],
       [7049.1325, 21.680000000000003],
       [11508.634, 22.2175],
       [8086.886, 21.78230769230769],
       [10072.1025, 21.92],
       [9001.401, 21.68],
       [5611.166, 20.29769230769231],
       [1887.989, 21.038571428571423],
       [17724.4535, 21.135714285714283],
       [4454.538, 21.14833333333333],
       [10278.756, 19.86642857142857],
       [9071.1825, 19.14555555555556],
       [1884.401, 19.121111111111112],
       [4634.284, 18.50076923076924],
       [5824.576499999999, 17.95111111111111],
       [1846.849, 11.412000000000004],
       [151.40249999999995, 0.165],
       [149.6085, 0.6525],
       [148.4725, 0.2],
       [149.37, 0.2477777777777777],
       [151.7615, 0.2681818181818181],
     

In [ ]:
import tensorflow as tf
y = tf.convert_to_tensor(y)
print(y)

ValueError: ignored

In [ ]:
x

array([[  6.,  40.,   1.,   0.],
       [  1., 165.,   1.,   1.],
       [  5.,  40.,   1.,   0.],
       ...,
       [  1.,   6.,   2.,   0.],
       [  3.,  32.,   2.,   0.],
       [  6.,  20.,   2.,   0.]])

In [ ]:
import torch
import numpy as np
y = float(y)
tensor = torch.from_numpy(y)
print(tensor)

TypeError: ignored

In [ ]:
model = models.Sequential()
model.add(layers.Dense(4, activation = 'relu',input_shape = (4,)))
model.add(layers.Dense(16,activation='relu'))
model.add(layers.Dense(8,activation='relu'))
model.add(layers.Dense(2,activation='relu'))
model.compile(optimizer='rmsprop' ,loss='categorical_crossentropy', metrics = ['accuracy'])

In [ ]:
model.fit(x,y,epochs=5,batch_size=150)

ValueError: ignored